### ISSUE TITLE
Bloom demo is broken

### ISSUE THREAD

**Issue by ASoldo** [Tresjs/post-processing#108]
When looking at docs for Bloom I can see empty canvas box with console message saying:
```md
framework.8oxMyIc2.js:1 TypeError: Class constructor ue cannot be invoked without 'new'
    at guide_effects_bloom.md.7kCtuEBS.js:1:914
    at Object.i [as default] (framework.8oxMyIc2.js:1:16078)
    at Proxy.<anonymous> (useRouteDisposal.tyh0ETgK.js:3645:321145)
    at ei (framework.8oxMyIc2.js:1:16394)
    at Mi.F [as fn] (framework.8oxMyIc2.js:1:49505)
    at Mi.run (framework.8oxMyIc2.js:1:4163)
    at B.p.update (framework.8oxMyIc2.js:1:49779)
    at B (framework.8oxMyIc2.js:1:49805)
    at ie (framework.8oxMyIc2.js:1:48650)
    at V (framework.8oxMyIc2.js:1:48444)
```

**Comment by Tinoooo** [comment]
will be fixed by #123
